module.exports={
    register:{
        'userName':'required|alpha_num',
        'email':'required|email',
        'password':'required|min:8',
        'profile.branch':'required'
    },
    login:{
        'userId':'required',
        'password':'required'

    },
    forgotPassword:{
        "email":"required|email"
    },
    posts:{
        'opID':"required",
        'postCategory':'required',
        'text':'required|max:240'
    }
};